[package]
name = "aerospace-rocketry-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
libm = "0.2"
ordered-float = { version = "5.1", default-features = false, features = ["libm"] }
thiserror = { version = "2.0", default-features = false }
